<?php

use App\Models\TeamModel;
use App\Models\UserModel;

/**
 * @var TeamModel[] $teams
 * @var UserModel[] $users
 * @var bool $canUpload
 */

/**
 * @param TeamModel $team
 * @return UserModel[]
 */
$findUsers = function (TeamModel $team) use (&$users) {
    return array_filter($users, function (UserModel $user) use ($team) {
        return $user->teamId == $team->id;
    });
};

$v->layout('layout', ['title' => 'Admin']);
?>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                Teams
                <form action="<?= route('add-team'); ?>" method="post" class="float-right">
                    <button type="submit" class="btn btn-primary btn-sm">Create a team</button>
                </form>
            </div>
            <div class="card-body">

                <div class="card-columns">
                    <?php foreach ($teams as $team) { ?>
                        <div class="card">
                            <div class="card-header p-1 pl-2">
                                <?= htmlspecialchars($team->name); ?>
                                (<?= $team->getReadableDistance(); ?>)
                                <form method="post" action="<?= route('delete-team'); ?>" class="float-right">
                                    <input type="hidden" name="teamId" value="<?= $team->id; ?>">
                                    <button type="submit" class="btn btn-link btn-sm m-0 p-0 mr-2">&times;</button>
                                </form>
                            </div>
                            <div class="card-body p-1 pl-2">
                                <?php
                                $teamUsers = $findUsers($team);
                                if (!$teamUsers) {
                                    ?><em class="text-muted">&ndash;</em><?php
                                } else {
                                    ?>
                                    <ul class="list-group list-group-flush">
                                        <?php foreach ($teamUsers as $u) { ?>
                                            <li class="list-group-item p-0">
                                                <a href="javascript:" class="impersonate" data-id="<?= $u->id; ?>"></a>
                                                <?= htmlspecialchars($u->name); ?>
                                                <form method="post" action="<?= route('unassign-team'); ?>"
                                                      class="float-right">
                                                    <input type="hidden" name="userId" value="<?= $u->id; ?>">
                                                    <button type="submit" class="btn btn-secondary btn-sm m-0 p-0 mr-2">
                                                        &times;
                                                    </button>
                                                </form>
                                            </li>
                                        <?php } ?>
                                    </ul>
                                    <?php
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                </div>

            </div>
        </div>
    </div>

    <div class="col-3">
        <div class="card <?= ($canUpload ? 'bg-success' : 'bg-danger'); ?> text-white mb-3">
            <div class="card-header">Activity upload</div>
            <div class="card-body">
                <form method="post" action="<?= route('enable-upload'); ?>">
                    <input type="hidden" name="canUpload" value="<?= ((int)!$canUpload); ?>">
                    <?php if ($canUpload) { ?>
                        <p>Activity upload is enabled.</p>
                        <button type="submit" class="btn p-1 btn-danger btn-block">Disable upload</button>
                    <?php } else { ?>
                        <p>Activity upload is disabled.</p>
                        <button type="submit" class="btn p-1 btn-success btn-block">Enable upload</button>
                    <?php } ?>
                </form>
            </div>
        </div>

        <div class="card">
            <div class="card-header">People without teams</div>
            <div class="card-body">
                <?php
                $teamlessUsers = $findUsers(new TeamModel);
                if (!$teamlessUsers) {
                    ?><em class="text-muted">&ndash;</em><?php
                } else {
                    ?>
                    <form action="<?= route('assign-team'); ?>" method="post">
                        <ul class="list-group list-group-flush">
                            <?php foreach ($teamlessUsers as $u) { ?>
                                <li class="list-group-item p-1">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" name="userIds[]"
                                               id="user<?= $u->id; ?>" value="<?= $u->id; ?>">
                                        <label class="custom-control-label d-block" for="user<?= $u->id; ?>">
                                            <a href="javascript:" class="impersonate" data-id="<?= $u->id; ?>"></a>
                                            <?= htmlspecialchars($u->name); ?>
                                        </label>
                                    </div>
                                </li>
                            <?php } ?>
                        </ul>
                        <select name="teamId" class="custom-select custom-select-sm mt-4">
                            <option value="0">-- Select a team --</option>
                            <?php foreach ($teams as $team) { ?>
                                <option value="<?= $team->id; ?>"><?= htmlspecialchars($team->name); ?></option>
                            <?php } ?>
                        </select>
                        <button type="submit" class="btn btn-primary btn-sm btn-block mt-2">Assign to a team
                        </button>
                    </form>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>

<form class="invisible" method="post" action="<?= route('impersonate'); ?>" id="form-impersonate">
    <input type="hidden" name="userId" id="impersonate">
</form>
<script>
    document.querySelectorAll('a.impersonate').forEach(function (a) {
        a.className += ' btn btn-link btn-sm p-0 m-0 mr-1';
        a.innerHTML = '&larr;';
        a.title = 'Impersonate';
        a.addEventListener('click', function (event) {
            if (confirm('Impersonate?')) {
                document.getElementById('impersonate').value = event.target.dataset.id;
                document.getElementById('form-impersonate').submit();
            }
        });
    });
</script>