<?php $v->layout('layout', ['title' => 'Board']) ?>

<div class="row">
    <div class="col"></div>
    <div class="col"></div>

    <div class="col">
        <div class="card">
            <div class="card-header"> Log an activity </div>
            <div class="card-body">
                <form action="/upload" method="post" enctype="multipart/form-data" id="gpx-form">
                    <div class="form-group">
                        <label for="customFile">Workout file (GPX):</label>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="gpx" id="customFile">
                            <label class="custom-file-label" id="custom-file-label" for="customFile">Select a
                                file...</label>
                        </div>
                        <small class="form-text text-muted">
                            How to export from
                            <a href="https://support.endomondo.com/hc/en-us/articles/213219528-File-Export"
                               target="_blank">Endomondo</a>
                            or
                            <a href="https://support.strava.com/hc/en-us/articles/216918437-Exporting-your-Data-and-Bulk-Export#GPX"
                               target="_blank">Strava</a>
                        </small>
                    </div>
                    <div class="form-group">
                        <label for="workoutUrl">Workout URL:</label>
                        <input type="url" class="form-control" name="workoutUrl" id="workoutUrl">
                        <small class="form-text text-muted">From your Endomondo or Strava workout page.</small>
                    </div>
                    <div class="form-group">
                        <label for="comment">Short comment:</label>
                        <input type="text" class="form-control" name="comment" id="comment">
                        <small class="form-text text-muted">Others will see this, make it motivational!</small>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-success">Upload</button>
                    </div>
                </form>
                <script>
                    document.getElementById('customFile').onchange = function () {
                        document.getElementById('custom-file-label').textContent = this.files[0].name;
                    };
                </script>
            </div>
        </div>
    </div>
</div>