<?php
/**
 * @var UserModel|null $user
 * @var string|null $_flash
 */

use App\Models\UserModel;

?>
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="<?= asset('bootstrap.min.css'); ?>?v=2">

    <script src="<?= asset('autosize.min.js'); ?>"></script>

    <title><?= $v($title); ?></title>
</head>
<body>

<div class="container pt-2">
    <?php if ($user) { ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="d-flex">
                    <div class="mr-3 mt-2 mb-1">
                        <a href="<?= route('board'); ?>" class="text-decoration-none">
                            <img src="<?= asset('logo.svg'); ?>" alt="" width="75">
                        </a>
                    </div>
                    <div class="mt-auto"><h2 class="m-0 p-0">Ready for the challenge?</h2></div>
                    <div class="ml-auto mt-auto">
                        <a class="btn btn-sm"><em><?= htmlspecialchars($user->name); ?></em></a>
                        <?php if ($user->isAdmin) { ?>
                            <a href="<?= route('admin'); ?>" class="btn btn-secondary btn-sm" role="button"
                               aria-pressed="true">
                                Admin
                            </a>
                        <?php } ?>
                        <a href="<?= route('logout'); ?>" class="btn btn-secondary btn-sm" role="button"
                           aria-pressed="true">
                            Sign out
                        </a>
                    </div>
                </div>
                <hr>
            </div>
        </div>
    <?php } ?>

    <?php if ($_flash) { ?>
        <div class="row">
            <div class="col-lg-12">
                <p class="alert alert-info"><?= $_flash; ?></p>
            </div>
        </div>
    <?php } ?>

    <div class="row">
        <div class="col-lg-12"><?= $v->section('content') ?></div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

