<?php
/**
 * @var UserModel|null $user
 * @var string|null $_flash
 */

use App\Models\UserModel;

?>
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/bootstrap.min.css">

    <title><?= $v($title); ?></title>
</head>
<body>

<div class="container pt-2">
    <?php if ($user) { ?>
        <div class="row">
            <div class="col">
                <h2>
                    <a href="/">Ready for the challenge?</a>

                    <div class="float-right mt-1">
                        <a class="btn btn-sm">
                            <em><?= htmlspecialchars($user->name); ?></em>
                        </a>
                        <?php if ($user->isAdmin) { ?>
                            <a href="/admin" class="btn btn-secondary btn-sm" role="button"
                               aria-pressed="true">
                                Admin
                            </a>
                        <?php } ?>
                        <a href="/logout" class="btn btn-secondary btn-sm" role="button"
                           aria-pressed="true">
                            Sign out
                        </a>
                    </div>
                </h2>
                <hr>
            </div>
        </div>
    <?php } ?>

    <?php if ($_flash) { ?>
        <div class="row">
            <div class="col">
                <p class="alert alert-info"><?= $_flash; ?></p>
            </div>
        </div>
    <?php } ?>

    <div class="row">
        <div class="col"><?= $v->section('content') ?></div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

