<?php

use App\Models\TotalsModel;

$v->layout('dashboard', ['title' => 'People']);
$v->push('card');

/**
 * @var TotalsModel[] $totals
 */

$i = 0;
?>
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Distance</th>
            <th scope="col">Activities</th>
            <th scope="col">Last Activity</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($totals as $a) { ?>
            <tr>
                <td><strong><?= ++$i; ?>.</strong></td>
                <td>
                    <b><?= htmlspecialchars($a->userName); ?></b>
                    <br>
                    <span class="badge p-0"><?= htmlspecialchars($a->teamName); ?></span>
                </td>
                <td><?= $a->getReadableDistance(); ?></td>
                <td class="text-center"><?= $a->activityCount; ?></td>
                <td><?= $a->getReadableLastActivityAt(); ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

<?php
$v->end();