<?php

use App\Models\ActivityModel;

$v->layout('dashboard', ['title' => 'My Activities']);
$v->push('card');

/**
 * @var ActivityModel[] $activities
 */

if ($activities) { ?>
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Distance</th>
            <th scope="col">Duration</th>
            <th scope="col">Average speed</th>
            <th scope="col">Date</th>
            <th scope="col">Uploaded</th>
            <th scope="col">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($activities as $a) { ?>
            <tr <?= ($a->deletedAt ? ' style="text-decoration: line-through;" class="text-muted"' : ''); ?>>
                <td><?= $a->getReadableDistance(); ?></td>
                <td><?= $a->getReadableDuration(); ?></td>
                <td><?= $a->getReadableSpeed(); ?></td>
                <td><?= $a->getReadableActivityAt(); ?></td>
                <td><?= $a->getReadableCreatedAt(); ?></td>
                <td class="text-right">
                    <?php if (!$a->deletedAt) { ?>
                        <form method="post" action="<?= route('delete-activity'); ?>" class="form-inline">
                            <input type="hidden" name="activityId" value="<?= $a->id; ?>">
                            <button type="submit" class="btn btn-link p-0 text-decoration-none"
                                    onclick="return confirm('Are you sure?');">❌
                            </button>
                        </form>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
<?php } else { ?>
    <h5 class="card-title">Hello, there!</h5>
    <p class="card-text">When you log an activity, it will show up here!</p>
    <?php
}
$v->end();