<?php

use App\Models\ActivityModel;

$v->layout('dashboard', ['title' => 'My Activites']);
$v->push('card');

/**
 * @var ActivityModel[] $activities
 */

if ($activities) { ?>
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Distance</th>
            <th scope="col">Duration</th>
            <th scope="col">Average speed</th>
            <th scope="col">Date</th>
            <th scope="col">Uploaded</th>
            <th scope="col">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($activities as $a) { ?>
            <tr>
                <td><?= $a->getReadableDistance(); ?></td>
                <td><?= $a->getReadableDuration(); ?></td>
                <td><?= $a->getReadableSpeed(); ?></td>
                <td><?= $a->getReadableActivityAt(); ?></td>
                <td><?= $a->getReadableCreatedAt(); ?></td>
                <td class="text-right">
                    <form method="post">
                        <input type="hidden" name="activityId" value="<?= $a->id; ?>">
                        <button type="submit" class="btn btn-sm btn-danger p-1 pt-0 pb-0"
                                onclick="return confirm('Sure?');">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
<?php } else { ?>
    <h5 class="card-title">Hello, there!</h5>
    <p class="card-text">When you log an activity, it will show up here!</p>
    <?php
}
$v->end();