<?php

use App\Models\TeamModel;
use App\Models\TotalsModel;
use App\Models\UserModel;

$v->layout('dashboard', ['title' => 'My Team']);
$v->push('card');

/**
 * @var TeamModel|null $team
 * @var TotalsModel[] $totals
 * @var UserModel[] $people
 */

if ($team) { ?>
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Distance</th>
            <th scope="col">Duration</th>
            <th scope="col">Activities</th>
            <th scope="col">Last Activity</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($totals as $a) { ?>
            <tr>
                <td><?= htmlspecialchars($a->userName); ?></td>
                <td><?= $a->getReadableDistance(); ?></td>
                <td><?= $a->getReadableDuration(); ?></td>
                <td><?= $a->activityCount; ?></td>
                <td><?= $a->getReadableLastActivityAt(); ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
<?php } else { ?>
    <h5 class="card-title">You are not in a team</h5>
    <p class="card-text">You will be assigned to a team soon, don't worry!</p>
    <?php
}
$v->end();

if ($team) {
    $v->push('after');
    ?>
    <div class="row mt-4">
        <div class="col-lg-8 mb-4">
            <?php $v->insert('_team-profile', ['team' => $team]); ?>
        </div>
        <div class="col mb-4">
            <?php $v->insert('_team-members', ['people' => $people]); ?>
        </div>
    </div>
    <?php
    $v->end();
}