<?php $v->layout('layout', ['title' => 'Register or Sign in']) ?>

<div class="alert alert-secondary" role="alert">
    Please sign in or register!
</div>

<div class="row">
    <div class="col-6">
        <form method="post" action="/register">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="email" id="email" aria-describedby="emailHelp"
                       placeholder="Enter email">
                <small id="emailHelp" class="form-text text-muted">Place where all the JIRA tasks end up</small>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                <small class="form-text text-muted">Sure, you can use the same password as for your PayPal
                    account.</small>
            </div>
            <div class="form-group">
                <label for="name">Your name (when registering only)</label>
                <input type="text" class="form-control" name="name" id="name" aria-describedby="emailHelp"
                       placeholder="Enter your name">
                <small class="form-text text-muted">What did your parents call you?</small>
            </div>
            <button type="submit" class="btn btn-danger">Sign in / Register</button>
        </form>
    </div>
</div>