<?php
use App\Models\ActivityModel;

/** @var string $title */

$v->layout('table', ['title' => $title]);
$v->push('table');

/**
 * @var ActivityModel $activity
 * @var array $coordinates
 * @var string $start
 * @var string $end
 * @var string $track
 */
$image = $activity->getImage();
$lastPoint = end($coordinates);
$firstPoint = reset($coordinates);
?>
<div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Distance</th>
            <th scope="col">Duration</th>
            <th scope="col">Average speed</th>
            <th scope="col">Date</th>
            <th scope="col">Uploaded</th>
            <th scope="col">Activity URL</th>
            <th scope="col">Comment</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="align-middle"><?= $activity->getReadableDistance(); ?></td>
            <td class="align-middle"><?= $activity->getReadableDuration(); ?></td>
            <td class="align-middle"><?= $activity->getReadableSpeed(); ?></td>
            <td class="align-middle"><?= $activity->getReadableActivityAt(); ?></td>
            <td class="align-middle"><?= $activity->getReadableCreatedAt(); ?></td>
            <td class="align-middle">
                <a href="<?=htmlspecialchars($activity->activityUrl);?>" target="_blank" rel="noopener noreferrer"><?= htmlspecialchars(minifyUrl($activity->activityUrl)); ?></a>
            </td>
            <td class="align-middle">
                <?= htmlspecialchars($activity->comment ?? ''); ?>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<div class="row">
    <div class="<?= $image ? 'col-lg-8' : 'col-lg-12';?>">
        <div class="row justify-content-center">
            <div class="<?= $image ? 'col-lg-10' : 'col-lg-8';?>">
                <div id="map" style="height: 600px;"></div>
            </div>
        </div>
    </div>
    <?php if ($image) { ?>
        <div class="col-lg-4">
            <img class="img-fluid" src="<?= $image->getLargeUrl();?>" alt=""/>
        </div>
    <?php } ?>
</div>
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
        var zoom = 13;
        var center = [<?=$firstPoint[0];?>, <?=$firstPoint[1];?>];

        var points = JSON.parse('<?= json_encode($coordinates);?>');

        var map = L.map('map').setView(center, zoom);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);

        var startIcon = new L.Icon({
            iconUrl: '/img/markers/marker-icon-2x-green.png',
            shadowUrl: '/img/markers/marker-shadow.png',
            iconSize: [25, 41],
            iconAnchor: [12, 41],
            popupAnchor: [1, -34],
            shadowSize: [41, 41]
        });

        var endIcon = new L.Icon({
            iconUrl: '/img/markers/marker-icon-2x-red.png',
            shadowUrl: '/img/markers/marker-shadow.png',
            iconSize: [25, 41],
            iconAnchor: [12, 41],
            popupAnchor: [1, -34],
            shadowSize: [41, 41]
        });

        var startMarker = L.marker(center, {icon: startIcon}).addTo(map).bindPopup('<p>Start:<br/><?=$start;?></p>');
        var endMarker = L.marker([<?=$lastPoint[0];?>, <?=$lastPoint[1];?>], {icon: endIcon})
            .addTo(map)
            .bindPopup('<p>End:<br/><?=$end;?></p>');

        var polyline = L.polyline(points, {color: 'red', opacity: 0.9})
            .bindPopup('<p>Track: <?=$track;?></p>')
            .addTo(map);
        map.fitBounds(polyline.getBounds());
    });
</script>
<?php $v->end(); ?>