<?php
use App\Models\ActivityModel;

/** @var string $title */

$v->layout('table', ['title' => $title]);
$v->push('table');

/**
 * @var ActivityModel[] $activities
 */
if ($activities) { ?>
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Distance</th>
            <th scope="col">Duration</th>
            <th scope="col">Average speed</th>
            <th scope="col">Date</th>
            <th scope="col">Uploaded</th>
            <th scope="col">Activity URL</th>
            <th scope="col">Comment</th>
            <th scope="col">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($activities as $a) {
            if ($a->deletedAt) {
                continue;
            }
            $image = $a->getImage();
            ?>
            <tr>
                <td>
                    <?php if ($image) { ?>
                        <a href="<?= $image->getLargeUrl(); ?>" class="btn btn-link p-0 mr-2 text-decoration-none"
                           target="_blank">
                            <img src="<?= $image->getSmallUrl(); ?>" alt="" height="30" class="align-middle">
                        </a>
                    <?php } ?>
                    <?= $a->getReadableDistance(); ?>
                </td>
                <td class="align-middle"><?= $a->getReadableDuration(); ?></td>
                <td class="align-middle"><?= $a->getReadableSpeed(); ?></td>
                <td class="align-middle"><?= $a->getReadableActivityAt(); ?></td>
                <td class="align-middle"><?= $a->getReadableCreatedAt(); ?></td>
                <td class="align-middle">
                    <a href="<?=htmlspecialchars($a->activityUrl);?>" target="_blank" rel="noopener noreferrer"><?= htmlspecialchars(minifyUrl($a->activityUrl)); ?></a>
                </td>
                <td class="align-middle">
                    <?= htmlspecialchars($a->comment ?? ''); ?>
                </td>
                <td class="align-middle text-right px-0">➡️</td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
<?php } else { ?>
    <p class="card-text">No activities found</p>
    <?php
}
$v->end();